### ISSUE TITLE
db:backup on db:up

### ISSUE THREAD

**Issue by ericclemmons** [evolution/generator-evolve#1]
Because `db:up` can override existing databases, use `:keep_releases` to indicate the number of DB backups to keep.

Probably no need (yet) to create a clean way of downloading them, but at least keeping rolling backups would be useful.

**Comment by EvanK** [comment]
1. Where should we put these rolling backups? In `/tmp`, or somewhere under `:deploy_to`?
2. Should we have a mechanism to disable this (eg, for sites with particularly large databases)?

**Comment by ericclemmons** [comment]
We usually have `/var/www/myproject.com/backups`, I thought..

**Comment by EvanK** [comment]
No, but we can add it, just right off of `:deploy_to`

**Comment by EvanK** [comment]
[RFC](https://github.com/evolution/wordpress/pull/3/files?w=1)
