### ISSUE TITLE
Log evolution commands

### ISSUE THREAD

**Issue by ericclemmons** [evolution/generator-evolve#2]
We're logging Apache, Pound, Varnish, PHP, etc., but no audit logs for _user_ actions.

I propose that we have specific logs for Evolution to see what users performed & when:

``` shell
Eric ~/wordpress-example $ bundle exec cap production evolve:db:up
Eric ~/wordpress-example $ bundle exec cap production evolve:ssh
Logged in as user "deploy".
deploy ~ $ tail /var/log/evolution/wordpress.log
...
2014-09-08 17:43 +600 UTC Eric evolve:restart...FAILED
2014-09-08 17:43 +600 UTC Eric evolve:db:up...SUCCESS
deploy ~ $ exit
```

/cc @EvanK

**Comment by EvanK** [comment]
I like it!

Somewhat related, we should probably set up logrotate for apache & other services that generate a significant amount of log data

**Comment by EvanK** [comment]
I'd presume we only want to log possibly destructive commands, so:
- `db:{up,down}`
- `files:{up,down}`
- `provision`
- `teardown`

And _maybe_ `wp:*` tasks?

**Comment by EvanK** [comment]
[RFC](https://github.com/evolution/wordpress/pull/2/files?w=1)

**Comment by ericclemmons** [comment]
Gotta use [hub](https://github.com/github/hub) to link PRs to existing issues!

`$ hub pull-request -i 2`

**Comment by EvanK** [comment]
An issue in one project to a PR in another?

**Comment by ericclemmons** [comment]
I'm an idiot.  I opened this issue in the wrong project :)
